service: saf-lambda-function
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"
  environment:
    BUCKET: ${env:BUCKET}

functions:
  saf-lambda-function:
    handler: handler.saf
    events:
      - s3: ${env:BUCKET}
    environment:
      COMMAND_STRING_INPUT: ${env:COMMAND_STRING_INPUT}

package:
  patterns:
    - '!.git/**'
    - '!.aws-sam/**'
    - '!node_modules/aws-sdk/**'
    - '!.idea/**'
