service: ${env:SERVICE_NAME, "saf-lambda-function"}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"
  environment:
    OUTPUT_BUCKET: ${env:OUTPUT_BUCKET}

functions:
  saf:
    handler: handler.saf
    events:
      - schedule: rate(2 minutes)
    environment:
      COMMAND_STRING: ${env:COMMAND_STRING}

package:
  patterns:
    - '!.git/**'
    - '!.aws-sam/**'
    - '!node_modules/aws-sdk/**'
    - '!.idea/**'
