service: ${env:SERVICE_NAME, "saf-lambda-function"}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      path: ${env:IAM_ROLE_PATH}
      permissionsBoundary: ${env:IAM_ROLE_BOUNDARY}
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"
  environment:
    OUTPUT_BUCKET: ${env:OUTPUT_BUCKET}

functions:
  saf:
    timeout: ${env:TIMEOUT, 900}
    handler: handler.saf
    events:
      - schedule: rate(3 minutes)
    environment:
      COMMAND_STRING: ${env:COMMAND_STRING}
      OUTPUT_PREFIX: ${env:OUTPUT_PREFIX, "results/"}
      OUTPUT_ENABLED: ${env:OUTPUT_ENABLED, "true"}

package:
  patterns:
    - '!.git/**'
    - '!.aws-sam/**'
    - '!node_modules/aws-sdk/**'
    - '!.idea/**'
