service: ${env:SERVICE_NAME, "saf-lambda-function"}
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "s3:*"
          Resource:
            - "*"
  environment:
    INPUT_BUCKET: ${env:INPUT_BUCKET}

functions:
  saf:
    handler: handler.saf
    events:
      - s3: 
          bucket: ${env:INPUT_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${env:INPUT_PREFIX, ""}
    environment:
      COMMAND_STRING: ${env:COMMAND_STRING}

package:
  patterns:
    - '!.git/**'
    - '!.aws-sam/**'
    - '!node_modules/aws-sdk/**'
    - '!.idea/**'
