name: Push SAF CLI to Docker Hub on every release

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-tag
        with:
          pattern: 'v'
          string: "${{ github.event.release.tag_name }}"
          replace-with: ''
          flags: 'g'
      - name: Checkout the SAF Repository
        uses: actions/checkout@v2 
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: mitre/saf:release-latest,mitre/saf:${{ steps.format-tag.outputs.replaced }},mitre/saf:v1