
name: Run Test Scripts
on:
  push:
    branches: main
  pull_request:


jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Install dependencies
      run: npm ci
    - name: Run Tests
      run: npm test
